//#line 2 "/opt/ros/melodic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"
// *********************************************************
//
// File autogenerated for the chapter9_tutorials package
// by the dynamic_reconfigure package.
// Please do not edit.
//
// ********************************************************/

#ifndef __chapter9_tutorials__HOMOGRAPHYCONFIG_H__
#define __chapter9_tutorials__HOMOGRAPHYCONFIG_H__

#if __cplusplus >= 201103L
#define DYNAMIC_RECONFIGURE_FINAL final
#else
#define DYNAMIC_RECONFIGURE_FINAL
#endif

#include <dynamic_reconfigure/config_tools.h>
#include <limits>
#include <ros/node_handle.h>
#include <dynamic_reconfigure/ConfigDescription.h>
#include <dynamic_reconfigure/ParamDescription.h>
#include <dynamic_reconfigure/Group.h>
#include <dynamic_reconfigure/config_init_mutex.h>
#include <boost/any.hpp>

namespace chapter9_tutorials
{
  class HomographyConfigStatics;

  class HomographyConfig
  {
  public:
    class AbstractParamDescription : public dynamic_reconfigure::ParamDescription
    {
    public:
      AbstractParamDescription(std::string n, std::string t, uint32_t l,
          std::string d, std::string e)
      {
        name = n;
        type = t;
        level = l;
        description = d;
        edit_method = e;
      }

      virtual void clamp(HomographyConfig &config, const HomographyConfig &max, const HomographyConfig &min) const = 0;
      virtual void calcLevel(uint32_t &level, const HomographyConfig &config1, const HomographyConfig &config2) const = 0;
      virtual void fromServer(const ros::NodeHandle &nh, HomographyConfig &config) const = 0;
      virtual void toServer(const ros::NodeHandle &nh, const HomographyConfig &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, HomographyConfig &config) const = 0;
      virtual void toMessage(dynamic_reconfigure::Config &msg, const HomographyConfig &config) const = 0;
      virtual void getValue(const HomographyConfig &config, boost::any &val) const = 0;
    };

    typedef boost::shared_ptr<AbstractParamDescription> AbstractParamDescriptionPtr;
    typedef boost::shared_ptr<const AbstractParamDescription> AbstractParamDescriptionConstPtr;

    // Final keyword added to class because it has virtual methods and inherits
    // from a class with a non-virtual destructor.
    template <class T>
    class ParamDescription DYNAMIC_RECONFIGURE_FINAL : public AbstractParamDescription
    {
    public:
      ParamDescription(std::string a_name, std::string a_type, uint32_t a_level,
          std::string a_description, std::string a_edit_method, T HomographyConfig::* a_f) :
        AbstractParamDescription(a_name, a_type, a_level, a_description, a_edit_method),
        field(a_f)
      {}

      T HomographyConfig::* field;

      virtual void clamp(HomographyConfig &config, const HomographyConfig &max, const HomographyConfig &min) const
      {
        if (config.*field > max.*field)
          config.*field = max.*field;

        if (config.*field < min.*field)
          config.*field = min.*field;
      }

      virtual void calcLevel(uint32_t &comb_level, const HomographyConfig &config1, const HomographyConfig &config2) const
      {
        if (config1.*field != config2.*field)
          comb_level |= level;
      }

      virtual void fromServer(const ros::NodeHandle &nh, HomographyConfig &config) const
      {
        nh.getParam(name, config.*field);
      }

      virtual void toServer(const ros::NodeHandle &nh, const HomographyConfig &config) const
      {
        nh.setParam(name, config.*field);
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, HomographyConfig &config) const
      {
        return dynamic_reconfigure::ConfigTools::getParameter(msg, name, config.*field);
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const HomographyConfig &config) const
      {
        dynamic_reconfigure::ConfigTools::appendParameter(msg, name, config.*field);
      }

      virtual void getValue(const HomographyConfig &config, boost::any &val) const
      {
        val = config.*field;
      }
    };

    class AbstractGroupDescription : public dynamic_reconfigure::Group
    {
      public:
      AbstractGroupDescription(std::string n, std::string t, int p, int i, bool s)
      {
        name = n;
        type = t;
        parent = p;
        state = s;
        id = i;
      }

      std::vector<AbstractParamDescriptionConstPtr> abstract_parameters;
      bool state;

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &config) const =0;
      virtual void updateParams(boost::any &cfg, HomographyConfig &top) const= 0;
      virtual void setInitialState(boost::any &cfg) const = 0;


      void convertParams()
      {
        for(std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = abstract_parameters.begin(); i != abstract_parameters.end(); ++i)
        {
          parameters.push_back(dynamic_reconfigure::ParamDescription(**i));
        }
      }
    };

    typedef boost::shared_ptr<AbstractGroupDescription> AbstractGroupDescriptionPtr;
    typedef boost::shared_ptr<const AbstractGroupDescription> AbstractGroupDescriptionConstPtr;

    // Final keyword added to class because it has virtual methods and inherits
    // from a class with a non-virtual destructor.
    template<class T, class PT>
    class GroupDescription DYNAMIC_RECONFIGURE_FINAL : public AbstractGroupDescription
    {
    public:
      GroupDescription(std::string a_name, std::string a_type, int a_parent, int a_id, bool a_s, T PT::* a_f) : AbstractGroupDescription(a_name, a_type, a_parent, a_id, a_s), field(a_f)
      {
      }

      GroupDescription(const GroupDescription<T, PT>& g): AbstractGroupDescription(g.name, g.type, g.parent, g.id, g.state), field(g.field), groups(g.groups)
      {
        parameters = g.parameters;
        abstract_parameters = g.abstract_parameters;
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &cfg) const
      {
        PT* config = boost::any_cast<PT*>(cfg);
        if(!dynamic_reconfigure::ConfigTools::getGroupState(msg, name, (*config).*field))
          return false;

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = &((*config).*field);
          if(!(*i)->fromMessage(msg, n))
            return false;
        }

        return true;
      }

      virtual void setInitialState(boost::any &cfg) const
      {
        PT* config = boost::any_cast<PT*>(cfg);
        T* group = &((*config).*field);
        group->state = state;

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = boost::any(&((*config).*field));
          (*i)->setInitialState(n);
        }

      }

      virtual void updateParams(boost::any &cfg, HomographyConfig &top) const
      {
        PT* config = boost::any_cast<PT*>(cfg);

        T* f = &((*config).*field);
        f->setParams(top, abstract_parameters);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = &((*config).*field);
          (*i)->updateParams(n, top);
        }
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &cfg) const
      {
        const PT config = boost::any_cast<PT>(cfg);
        dynamic_reconfigure::ConfigTools::appendGroup<T>(msg, name, id, parent, config.*field);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          (*i)->toMessage(msg, config.*field);
        }
      }

      T PT::* field;
      std::vector<HomographyConfig::AbstractGroupDescriptionConstPtr> groups;
    };

class DEFAULT
{
  public:
    DEFAULT()
    {
      state = true;
      name = "Default";
    }

    void setParams(HomographyConfig &config, const std::vector<AbstractParamDescriptionConstPtr> params)
    {
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator _i = params.begin(); _i != params.end(); ++_i)
      {
        boost::any val;
        (*_i)->getValue(config, val);

        if("detector"==(*_i)->name){detector = boost::any_cast<std::string>(val);}
        if("descriptor"==(*_i)->name){descriptor = boost::any_cast<std::string>(val);}
        if("matcher"==(*_i)->name){matcher = boost::any_cast<std::string>(val);}
        if("filter"==(*_i)->name){filter = boost::any_cast<std::string>(val);}
        if("threshold"==(*_i)->name){threshold = boost::any_cast<double>(val);}
      }
    }

    std::string detector;
std::string descriptor;
std::string matcher;
std::string filter;
double threshold;

    bool state;
    std::string name;

    
}groups;



//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      std::string detector;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      std::string descriptor;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      std::string matcher;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      std::string filter;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double threshold;
//#line 228 "/opt/ros/melodic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"

    bool __fromMessage__(dynamic_reconfigure::Config &msg)
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();

      int count = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        if ((*i)->fromMessage(msg, *this))
          count++;

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i ++)
      {
        if ((*i)->id == 0)
        {
          boost::any n = boost::any(this);
          (*i)->updateParams(n, *this);
          (*i)->fromMessage(msg, n);
        }
      }

      if (count != dynamic_reconfigure::ConfigTools::size(msg))
      {
        ROS_ERROR("HomographyConfig::__fromMessage__ called with an unexpected parameter.");
        ROS_ERROR("Booleans:");
        for (unsigned int i = 0; i < msg.bools.size(); i++)
          ROS_ERROR("  %s", msg.bools[i].name.c_str());
        ROS_ERROR("Integers:");
        for (unsigned int i = 0; i < msg.ints.size(); i++)
          ROS_ERROR("  %s", msg.ints[i].name.c_str());
        ROS_ERROR("Doubles:");
        for (unsigned int i = 0; i < msg.doubles.size(); i++)
          ROS_ERROR("  %s", msg.doubles[i].name.c_str());
        ROS_ERROR("Strings:");
        for (unsigned int i = 0; i < msg.strs.size(); i++)
          ROS_ERROR("  %s", msg.strs[i].name.c_str());
        // @todo Check that there are no duplicates. Make this error more
        // explicit.
        return false;
      }
      return true;
    }

    // This version of __toMessage__ is used during initialization of
    // statics when __getParamDescriptions__ can't be called yet.
    void __toMessage__(dynamic_reconfigure::Config &msg, const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__, const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__) const
    {
      dynamic_reconfigure::ConfigTools::clear(msg);
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->toMessage(msg, *this);

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); ++i)
      {
        if((*i)->id == 0)
        {
          (*i)->toMessage(msg, *this);
        }
      }
    }

    void __toMessage__(dynamic_reconfigure::Config &msg) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      __toMessage__(msg, __param_descriptions__, __group_descriptions__);
    }

    void __toServer__(const ros::NodeHandle &nh) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->toServer(nh, *this);
    }

    void __fromServer__(const ros::NodeHandle &nh)
    {
      static bool setup=false;

      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->fromServer(nh, *this);

      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i++){
        if (!setup && (*i)->id == 0) {
          setup = true;
          boost::any n = boost::any(this);
          (*i)->setInitialState(n);
        }
      }
    }

    void __clamp__()
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const HomographyConfig &__max__ = __getMax__();
      const HomographyConfig &__min__ = __getMin__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->clamp(*this, __max__, __min__);
    }

    uint32_t __level__(const HomographyConfig &config) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      uint32_t level = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->calcLevel(level, config, *this);
      return level;
    }

    static const dynamic_reconfigure::ConfigDescription &__getDescriptionMessage__();
    static const HomographyConfig &__getDefault__();
    static const HomographyConfig &__getMax__();
    static const HomographyConfig &__getMin__();
    static const std::vector<AbstractParamDescriptionConstPtr> &__getParamDescriptions__();
    static const std::vector<AbstractGroupDescriptionConstPtr> &__getGroupDescriptions__();

  private:
    static const HomographyConfigStatics *__get_statics__();
  };

  template <> // Max and min are ignored for strings.
  inline void HomographyConfig::ParamDescription<std::string>::clamp(HomographyConfig &config, const HomographyConfig &max, const HomographyConfig &min) const
  {
    (void) config;
    (void) min;
    (void) max;
    return;
  }

  class HomographyConfigStatics
  {
    friend class HomographyConfig;

    HomographyConfigStatics()
    {
HomographyConfig::GroupDescription<HomographyConfig::DEFAULT, HomographyConfig> Default("Default", "", 0, 0, true, &HomographyConfig::groups);
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.detector = "";
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.detector = "";
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.detector = "ORB";
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(HomographyConfig::AbstractParamDescriptionConstPtr(new HomographyConfig::ParamDescription<std::string>("detector", "str", 0, "Feature detector.", "{'enum_description': 'Feature detectors.', 'enum': [{'srcline': 11, 'description': 'FAST', 'srcfile': '/home/kimsanggil/study_ws/src/chapter9_tutorials/cfg/Homography.cfg', 'cconsttype': 'const char * const', 'value': 'FAST', 'ctype': 'std::string', 'type': 'str', 'name': 'FAST'}, {'srcline': 12, 'description': 'Good Features To Track', 'srcfile': '/home/kimsanggil/study_ws/src/chapter9_tutorials/cfg/Homography.cfg', 'cconsttype': 'const char * const', 'value': 'GFTT', 'ctype': 'std::string', 'type': 'str', 'name': 'GFTT'}, {'srcline': 13, 'description': 'Maximal Stable Extremal Regions', 'srcfile': '/home/kimsanggil/study_ws/src/chapter9_tutorials/cfg/Homography.cfg', 'cconsttype': 'const char * const', 'value': 'MSER', 'ctype': 'std::string', 'type': 'str', 'name': 'MSER'}, {'srcline': 14, 'description': 'ORiented BRIEF', 'srcfile': '/home/kimsanggil/study_ws/src/chapter9_tutorials/cfg/Homography.cfg', 'cconsttype': 'const char * const', 'value': 'ORB', 'ctype': 'std::string', 'type': 'str', 'name': 'ORB'}, {'srcline': 15, 'description': 'SIFT', 'srcfile': '/home/kimsanggil/study_ws/src/chapter9_tutorials/cfg/Homography.cfg', 'cconsttype': 'const char * const', 'value': 'SIFT', 'ctype': 'std::string', 'type': 'str', 'name': 'SIFT'}, {'srcline': 16, 'description': 'STAR', 'srcfile': '/home/kimsanggil/study_ws/src/chapter9_tutorials/cfg/Homography.cfg', 'cconsttype': 'const char * const', 'value': 'STAR', 'ctype': 'std::string', 'type': 'str', 'name': 'STAR'}, {'srcline': 17, 'description': 'SURF', 'srcfile': '/home/kimsanggil/study_ws/src/chapter9_tutorials/cfg/Homography.cfg', 'cconsttype': 'const char * const', 'value': 'SURF', 'ctype': 'std::string', 'type': 'str', 'name': 'SURF'}]}", &HomographyConfig::detector)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(HomographyConfig::AbstractParamDescriptionConstPtr(new HomographyConfig::ParamDescription<std::string>("detector", "str", 0, "Feature detector.", "{'enum_description': 'Feature detectors.', 'enum': [{'srcline': 11, 'description': 'FAST', 'srcfile': '/home/kimsanggil/study_ws/src/chapter9_tutorials/cfg/Homography.cfg', 'cconsttype': 'const char * const', 'value': 'FAST', 'ctype': 'std::string', 'type': 'str', 'name': 'FAST'}, {'srcline': 12, 'description': 'Good Features To Track', 'srcfile': '/home/kimsanggil/study_ws/src/chapter9_tutorials/cfg/Homography.cfg', 'cconsttype': 'const char * const', 'value': 'GFTT', 'ctype': 'std::string', 'type': 'str', 'name': 'GFTT'}, {'srcline': 13, 'description': 'Maximal Stable Extremal Regions', 'srcfile': '/home/kimsanggil/study_ws/src/chapter9_tutorials/cfg/Homography.cfg', 'cconsttype': 'const char * const', 'value': 'MSER', 'ctype': 'std::string', 'type': 'str', 'name': 'MSER'}, {'srcline': 14, 'description': 'ORiented BRIEF', 'srcfile': '/home/kimsanggil/study_ws/src/chapter9_tutorials/cfg/Homography.cfg', 'cconsttype': 'const char * const', 'value': 'ORB', 'ctype': 'std::string', 'type': 'str', 'name': 'ORB'}, {'srcline': 15, 'description': 'SIFT', 'srcfile': '/home/kimsanggil/study_ws/src/chapter9_tutorials/cfg/Homography.cfg', 'cconsttype': 'const char * const', 'value': 'SIFT', 'ctype': 'std::string', 'type': 'str', 'name': 'SIFT'}, {'srcline': 16, 'description': 'STAR', 'srcfile': '/home/kimsanggil/study_ws/src/chapter9_tutorials/cfg/Homography.cfg', 'cconsttype': 'const char * const', 'value': 'STAR', 'ctype': 'std::string', 'type': 'str', 'name': 'STAR'}, {'srcline': 17, 'description': 'SURF', 'srcfile': '/home/kimsanggil/study_ws/src/chapter9_tutorials/cfg/Homography.cfg', 'cconsttype': 'const char * const', 'value': 'SURF', 'ctype': 'std::string', 'type': 'str', 'name': 'SURF'}]}", &HomographyConfig::detector)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.descriptor = "";
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.descriptor = "";
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.descriptor = "SURF";
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(HomographyConfig::AbstractParamDescriptionConstPtr(new HomographyConfig::ParamDescription<std::string>("descriptor", "str", 0, "Descriptor extractor.", "{'enum_description': 'Descriptor extractors.', 'enum': [{'srcline': 15, 'description': 'SIFT', 'srcfile': '/home/kimsanggil/study_ws/src/chapter9_tutorials/cfg/Homography.cfg', 'cconsttype': 'const char * const', 'value': 'SIFT', 'ctype': 'std::string', 'type': 'str', 'name': 'SIFT'}, {'srcline': 17, 'description': 'SURF', 'srcfile': '/home/kimsanggil/study_ws/src/chapter9_tutorials/cfg/Homography.cfg', 'cconsttype': 'const char * const', 'value': 'SURF', 'ctype': 'std::string', 'type': 'str', 'name': 'SURF'}]}", &HomographyConfig::descriptor)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(HomographyConfig::AbstractParamDescriptionConstPtr(new HomographyConfig::ParamDescription<std::string>("descriptor", "str", 0, "Descriptor extractor.", "{'enum_description': 'Descriptor extractors.', 'enum': [{'srcline': 15, 'description': 'SIFT', 'srcfile': '/home/kimsanggil/study_ws/src/chapter9_tutorials/cfg/Homography.cfg', 'cconsttype': 'const char * const', 'value': 'SIFT', 'ctype': 'std::string', 'type': 'str', 'name': 'SIFT'}, {'srcline': 17, 'description': 'SURF', 'srcfile': '/home/kimsanggil/study_ws/src/chapter9_tutorials/cfg/Homography.cfg', 'cconsttype': 'const char * const', 'value': 'SURF', 'ctype': 'std::string', 'type': 'str', 'name': 'SURF'}]}", &HomographyConfig::descriptor)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.matcher = "";
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.matcher = "";
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.matcher = "FlannBased";
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(HomographyConfig::AbstractParamDescriptionConstPtr(new HomographyConfig::ParamDescription<std::string>("matcher", "str", 0, "Descriptor matcher.", "{'enum_description': 'Descriptor matchers.', 'enum': [{'srcline': 28, 'description': 'BruteForce', 'srcfile': '/home/kimsanggil/study_ws/src/chapter9_tutorials/cfg/Homography.cfg', 'cconsttype': 'const char * const', 'value': 'BruteForce', 'ctype': 'std::string', 'type': 'str', 'name': 'BruteForce'}, {'srcline': 29, 'description': 'FlannBased', 'srcfile': '/home/kimsanggil/study_ws/src/chapter9_tutorials/cfg/Homography.cfg', 'cconsttype': 'const char * const', 'value': 'FlannBased', 'ctype': 'std::string', 'type': 'str', 'name': 'FlannBased'}]}", &HomographyConfig::matcher)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(HomographyConfig::AbstractParamDescriptionConstPtr(new HomographyConfig::ParamDescription<std::string>("matcher", "str", 0, "Descriptor matcher.", "{'enum_description': 'Descriptor matchers.', 'enum': [{'srcline': 28, 'description': 'BruteForce', 'srcfile': '/home/kimsanggil/study_ws/src/chapter9_tutorials/cfg/Homography.cfg', 'cconsttype': 'const char * const', 'value': 'BruteForce', 'ctype': 'std::string', 'type': 'str', 'name': 'BruteForce'}, {'srcline': 29, 'description': 'FlannBased', 'srcfile': '/home/kimsanggil/study_ws/src/chapter9_tutorials/cfg/Homography.cfg', 'cconsttype': 'const char * const', 'value': 'FlannBased', 'ctype': 'std::string', 'type': 'str', 'name': 'FlannBased'}]}", &HomographyConfig::matcher)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.filter = "";
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.filter = "";
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.filter = "CrossCheckFilter";
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(HomographyConfig::AbstractParamDescriptionConstPtr(new HomographyConfig::ParamDescription<std::string>("filter", "str", 0, "Matcher filter.", "{'enum_description': 'Matcher filters.', 'enum': [{'srcline': 35, 'description': 'NoneFilter', 'srcfile': '/home/kimsanggil/study_ws/src/chapter9_tutorials/cfg/Homography.cfg', 'cconsttype': 'const char * const', 'value': 'NoneFilter', 'ctype': 'std::string', 'type': 'str', 'name': 'NoneFilter'}, {'srcline': 36, 'description': 'CrossCheckFilter', 'srcfile': '/home/kimsanggil/study_ws/src/chapter9_tutorials/cfg/Homography.cfg', 'cconsttype': 'const char * const', 'value': 'CrossCheckFilter', 'ctype': 'std::string', 'type': 'str', 'name': 'CrossCheckFilter'}]}", &HomographyConfig::filter)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(HomographyConfig::AbstractParamDescriptionConstPtr(new HomographyConfig::ParamDescription<std::string>("filter", "str", 0, "Matcher filter.", "{'enum_description': 'Matcher filters.', 'enum': [{'srcline': 35, 'description': 'NoneFilter', 'srcfile': '/home/kimsanggil/study_ws/src/chapter9_tutorials/cfg/Homography.cfg', 'cconsttype': 'const char * const', 'value': 'NoneFilter', 'ctype': 'std::string', 'type': 'str', 'name': 'NoneFilter'}, {'srcline': 36, 'description': 'CrossCheckFilter', 'srcfile': '/home/kimsanggil/study_ws/src/chapter9_tutorials/cfg/Homography.cfg', 'cconsttype': 'const char * const', 'value': 'CrossCheckFilter', 'ctype': 'std::string', 'type': 'str', 'name': 'CrossCheckFilter'}]}", &HomographyConfig::filter)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.threshold = 0.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.threshold = 10.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.threshold = 1.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(HomographyConfig::AbstractParamDescriptionConstPtr(new HomographyConfig::ParamDescription<double>("threshold", "double", 0, "RANSAC reprojection threshold.", "", &HomographyConfig::threshold)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(HomographyConfig::AbstractParamDescriptionConstPtr(new HomographyConfig::ParamDescription<double>("threshold", "double", 0, "RANSAC reprojection threshold.", "", &HomographyConfig::threshold)));
//#line 246 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.convertParams();
//#line 246 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __group_descriptions__.push_back(HomographyConfig::AbstractGroupDescriptionConstPtr(new HomographyConfig::GroupDescription<HomographyConfig::DEFAULT, HomographyConfig>(Default)));
//#line 366 "/opt/ros/melodic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"

      for (std::vector<HomographyConfig::AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); ++i)
      {
        __description_message__.groups.push_back(**i);
      }
      __max__.__toMessage__(__description_message__.max, __param_descriptions__, __group_descriptions__);
      __min__.__toMessage__(__description_message__.min, __param_descriptions__, __group_descriptions__);
      __default__.__toMessage__(__description_message__.dflt, __param_descriptions__, __group_descriptions__);
    }
    std::vector<HomographyConfig::AbstractParamDescriptionConstPtr> __param_descriptions__;
    std::vector<HomographyConfig::AbstractGroupDescriptionConstPtr> __group_descriptions__;
    HomographyConfig __max__;
    HomographyConfig __min__;
    HomographyConfig __default__;
    dynamic_reconfigure::ConfigDescription __description_message__;

    static const HomographyConfigStatics *get_instance()
    {
      // Split this off in a separate function because I know that
      // instance will get initialized the first time get_instance is
      // called, and I am guaranteeing that get_instance gets called at
      // most once.
      static HomographyConfigStatics instance;
      return &instance;
    }
  };

  inline const dynamic_reconfigure::ConfigDescription &HomographyConfig::__getDescriptionMessage__()
  {
    return __get_statics__()->__description_message__;
  }

  inline const HomographyConfig &HomographyConfig::__getDefault__()
  {
    return __get_statics__()->__default__;
  }

  inline const HomographyConfig &HomographyConfig::__getMax__()
  {
    return __get_statics__()->__max__;
  }

  inline const HomographyConfig &HomographyConfig::__getMin__()
  {
    return __get_statics__()->__min__;
  }

  inline const std::vector<HomographyConfig::AbstractParamDescriptionConstPtr> &HomographyConfig::__getParamDescriptions__()
  {
    return __get_statics__()->__param_descriptions__;
  }

  inline const std::vector<HomographyConfig::AbstractGroupDescriptionConstPtr> &HomographyConfig::__getGroupDescriptions__()
  {
    return __get_statics__()->__group_descriptions__;
  }

  inline const HomographyConfigStatics *HomographyConfig::__get_statics__()
  {
    const static HomographyConfigStatics *statics;

    if (statics) // Common case
      return statics;

    boost::mutex::scoped_lock lock(dynamic_reconfigure::__init_mutex__);

    if (statics) // In case we lost a race.
      return statics;

    statics = HomographyConfigStatics::get_instance();

    return statics;
  }

//#line 11 "/home/kimsanggil/study_ws/src/chapter9_tutorials/cfg/Homography.cfg"
      const char * const Homography_FAST = "FAST";
//#line 12 "/home/kimsanggil/study_ws/src/chapter9_tutorials/cfg/Homography.cfg"
      const char * const Homography_GFTT = "GFTT";
//#line 13 "/home/kimsanggil/study_ws/src/chapter9_tutorials/cfg/Homography.cfg"
      const char * const Homography_MSER = "MSER";
//#line 14 "/home/kimsanggil/study_ws/src/chapter9_tutorials/cfg/Homography.cfg"
      const char * const Homography_ORB = "ORB";
//#line 15 "/home/kimsanggil/study_ws/src/chapter9_tutorials/cfg/Homography.cfg"
      const char * const Homography_SIFT = "SIFT";
//#line 16 "/home/kimsanggil/study_ws/src/chapter9_tutorials/cfg/Homography.cfg"
      const char * const Homography_STAR = "STAR";
//#line 17 "/home/kimsanggil/study_ws/src/chapter9_tutorials/cfg/Homography.cfg"
      const char * const Homography_SURF = "SURF";
//#line 28 "/home/kimsanggil/study_ws/src/chapter9_tutorials/cfg/Homography.cfg"
      const char * const Homography_BruteForce = "BruteForce";
//#line 29 "/home/kimsanggil/study_ws/src/chapter9_tutorials/cfg/Homography.cfg"
      const char * const Homography_FlannBased = "FlannBased";
//#line 35 "/home/kimsanggil/study_ws/src/chapter9_tutorials/cfg/Homography.cfg"
      const char * const Homography_NoneFilter = "NoneFilter";
//#line 36 "/home/kimsanggil/study_ws/src/chapter9_tutorials/cfg/Homography.cfg"
      const char * const Homography_CrossCheckFilter = "CrossCheckFilter";
}

#undef DYNAMIC_RECONFIGURE_FINAL

#endif // __HOMOGRAPHYRECONFIGURATOR_H__
